### ISSUE TITLE
NSE is changing the cash market file format

### ISSUE THREAD

**Issue by MSurenBabu** [touchofevil-dev/BhavcopyEasy#10]
Dear Developer,

NSE is changing the cash market file format. We need to change our tool to take the new format as input to generate the EoD file. Please find the attached file for your reference. Request to kindly make the appropriate changes before the deadline, 8th July'24.

The new file format has all the information present in the old format. We need to look for the different columns to get it.

![brave_aAlnul8uaG](https://github.com/touchofevil-dev/BhavcopyEasy/assets/117297239/a7cb07a5-9488-4f5d-8d5d-79f440fde53b)

New file format with the old format columns marked for your reference.

[BhavCopy_NSE_CM_0_0_0_20240620_F_0000.xlsx](https://github.com/user-attachments/files/15915055/BhavCopy_NSE_CM_0_0_0_20240620_F_0000.xlsx)

**Comment by touchofevil-dev** [comment]
@MSurenBabu - Thanks for reporting this. This is already being worked upon, and should be available in the upcoming week.

**Comment by MSurenBabu** [comment]
Thanks, @touchofevil-dev for the response. I don't know where to put it as an enhancement, so I submitted it as an issue — pl excuse. I will be eagerly waiting for your update.

**Comment by touchofevil-dev** [comment]
@MSurenBabu - No problem, you've done the right thing. Tagging is just to help me out on my priorities. Don't worry about it.
Btw, this feature is [now available](https://github.com/touchofevil-dev/BhavcopyEasy/releases/tag/v1.2.0). Please feel free to let me know if any issues.

**Comment by MSurenBabu** [comment]
Thanks for the update on time @touchofevil-dev. I tried with today's new format file and worked file. I also compared the old file (# of rows are the same. Other than that, as the new format is not sorted when compared to the old format, I couldn't do any other verification). I will keep using the new one and will surely get back to any issues.

Thanks again for your efforts. Highly appreciated.
