### ISSUE TITLE
i can't install, means "install" button shows "grey" any help...

### ISSUE THREAD

**Issue by madhanji** [touchofevil-dev/BhavcopyEasy#6]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by touchofevil-dev** [comment]
Please check the description and readme file in this repo. It already mentions the necessary steps.
Closing as not an issue, however feel free to open it if that doesn't solve your problem.
