### ISSUE TITLE
Issue with 1.0 release with install

### ISSUE THREAD

**Issue by MSurenBabu** [touchofevil-dev/BhavcopyEasy#7]
![image](https://github.com/touchofevil-dev/BhavcopyEasy/assets/117297239/ed15c950-1c39-4f2f-b87f-0b5af68d88a7)

I get this error message. Install button is not enabled. Could you pl help me.

**Comment by touchofevil-dev** [comment]
@MSurenBabu check out this link on the readme file. This is a one time operation you'll have to perform.

https://github.com/touchofevil-dev/BhavcopyEasy/tree/v1.0.0#if-installation-button-is-disabled

I am closing this issue for now, however feel free to reopen in case if you face further challenges.

**Comment by MSurenBabu** [comment]
Sorry for the late response. It did worked and I have been using your software everyday for amibroker update. Thanks for the utility.

Couple of things could be planned in  future based on your available time:
1. Remember the last File Location and Output Location. So that we don't need to select it everytime
2. Utility to download the data and index data on just selecting the date / dates.

These would go long way in the usefulness of the software.

Thanks again for your efforts.

**Comment by touchofevil-dev** [comment]
@MSurenBabu  - Thanks for trying it out and providing suggestions. It definitely helps.

1. I am already working on this. I have been a little occupied so couldn't release the updates but should have that very soon.
2. This is something I am currently investigating post recent changes of NSE. It is something I would like to have for sure.

Thanks again for using the utility and keep providing feature suggestions. I can't promise to implement everything but we can definitely evaluate and expand feature list as necessary.

**Comment by touchofevil-dev** [comment]
@MSurenBabu - Not sure if you've noticed but I've released v1.1.0 that should now allow you to setup input output folders.

**Comment by MSurenBabu** [comment]
> @MSurenBabu - Not sure if you've noticed but I've released v1.1.0 that should now allow you to setup input output folders.

Hi,

I have been using this tool all along since it was available. Today, for some reason it is not working. Though the settings has the input and output folder, it says missing for some reason. Due to this, I'm unable to generate the file. Request to kindly look into the issue. Pl feel free to get in touch for any additional information for trouble shooting.
![bhavcopyeasy_J7X8Jxwz86](https://github.com/touchofevil-dev/BhavcopyEasy/assets/117297239/a4254f1c-1da7-4230-bdc4-03187b0d99a4)

**Comment by touchofevil-dev** [comment]
@MSurenBabu - Could you try saving the settings explicitly? Also please check if the paths shown are correct and exist. Could you also try changing the location of those paths?
Also curious, has something changed? Moved folders or such? Since this app doesn't auto update, wondering how it changed all of a sudden.
Also if your output folder is correct, see if it has generated an error.txt, if yes you can attach that file in comment.

**Comment by MSurenBabu** [comment]
> @MSurenBabu - Could you try saving the settings explicitly? 

//
I did that. Some thing strange, all i did before this issue is changing the input folder and something went wrong. All along I didn't change the settings earlier.
//

Also please check if the paths shown are correct and exist. Could you also try changing the location of those paths? 

//
I tried different paths with combinations. Nothing helped. 
//

Also curious, has something changed? Moved folders or such? Since this app doesn't auto update, wondering how it changed all of a sudden. Also if your output folder is correct, see if it has generated an error.txt, if yes you can attach that file in comment.

//
Not moved any folder and folder are selected by clicking. I didn't typed it. Also, no error file as well. Once this msg comes in the app as shown in the snapshot i attached in my earlier comment, 'Generate files' button never worked.

I tried reinstall over the earlier installation and no change. Then, what worked for me just now is, uninstalled the old one, restarted OS, installed fresh and it worked. It saves the path and no error msg.

Thanks for your prompt response. Appreciate your efforts.
//

**Comment by MSurenBabu** [comment]
Today I could able to replicate the issue:

1. You continue to have some settings of X and Y as input and output folder and have been generating files all alonng.
2. Now, run the bhavcopyeasy tool, go to settings, change  the input and output folder, save it and then press 'Generate file' button. It throws the error 'Missing settings....'.
3. Once you get this msg, there is no way to get it to work. In my first attempt I uninstalled, restarted OS, fresh installation done and it worked. 
4. Can you tell me where to look for the log file. It is not in input/output folder, though. 
5. Pl check it.

**Comment by touchofevil-dev** [comment]
Thanks for these steps. I will take a look at these and get this sorted soon.

**Comment by MSurenBabu** [comment]
I got the root cause of the issue. It is in settings.json file.

Problematic settings.json: {"InputLocation":"D:\\Downloads","OutputLocation":"D:\\Data\\NSE EoD"}\\Data\\NSE EoD\\2016"}

Fixed setings.json: {"InputLocation":"D:\\Downloads","OutputLocation":"D:\\Data\\NSE EoD"}

You could fix in the code when there is a change in input/output folder it is getting corrupted.

**Comment by touchofevil-dev** [comment]
@MSurenBabu - Yes I thought it might have something to do with that. I was thinking of getting that changed once you mentioned that issue first, but glad you've provided further information. I will work this one soon, but won't be before the weekend as its a bit hectic for me currently. Thanks for all the details you've added.

**Comment by MSurenBabu** [comment]
> @MSurenBabu - Yes I thought it might have something to do with that. I was thinking of getting that changed once you mentioned that issue first, but glad you've provided further information. I will work this one soon, but won't be before the weekend as its a bit hectic for me currently. Thanks for all the details you've added.

Thanks for your prompt response.

Take your own time. Now, we know if we do change the folder, what needs to be done manually to fix it.

**Comment by touchofevil-dev** [comment]
> > @MSurenBabu - Yes I thought it might have something to do with that. I was thinking of getting that changed once you mentioned that issue first, but glad you've provided further information. I will work this one soon, but won't be before the weekend as its a bit hectic for me currently. Thanks for all the details you've added.
> 
> Thanks for your prompt response.
> 
> Take your own time. Now, we know if we do change the folder, what needs to be done manually to fix it.

@MSurenBabu - I have just released this fix. Could you try latest? Let me know if you have any issues installing it. Do [check this](https://github.com/touchofevil-dev/BhavcopyEasy/tree/v1.0.0#if-installation-button-is-disabled) if any issue on installation.
